name: Run Telegram Finder (Scheduled)

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  run_telegram_bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pyrogram

    - name: Decrypt Telegram Session File
      env:
        PASSPHRASE: ${{ secrets.DECRYPTION }}
      run: |
        echo "$PASSPHRASE" | gpg --quiet --batch --yes --decrypt --passphrase-fd 0 --output telegram.session telegram.session.aes256 || { echo "Telegram decryption failed!"; exit 1; }
      shell: bash

    - name: Run finder.py
      run: python finder.py

    - name: Commit and Push generated files
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        git add configs.txt
        if ! git diff-index --quiet HEAD; then
          git commit -m "feat: Automated update of generated files"
          git pull --rebase origin main
          git push
        else
          echo "No changes to commit"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
